[General]
# (optional) where to log mavlink traffic
Log=/dev/null

# Input comes from SITL on UDP 14540
[UdpEndpoint SITL]
Mode = Server
Address = 127.0.0.1
Port = 14550

# Fan‑out to your pymavlink script on UDP 14551
[UdpEndpoint MAVROS]
Mode = Normal
Address = 127.0.0.1
Port = 14551

[UdpEndpoint QGC]
Mode = Normal
Address = 127.0.0.1
Port = 14552

[UdpEndpoint MAVSDK]
Mode = Normal
Address = 127.0.0.1
Port = 14553


